language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.4.3
  - DJANGO_VERSION=1.5
install:
  - "if [[ $DJANGO_VERSION == '1.5' ]]; then pip install https://www.djangoproject.com/download/1.5c2/tarball/; else pip install Django==$DJANGO_VERSION; fi"
  - "pip install . --use-mirrors"
  - "pip install https://github.com/leukeleu/django-multilingual-ds9/tarball/0.3.0.6"
  - "pip install -r testproject/requirements.txt --use-mirrors"
script:
  - cd testproject
  - mkdir -p reports
  - python manage.py jenkins
branches:
  only:
    - multilingual