language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=Django==1.4.13
  - DJANGO=Django==1.5.8
  - DJANGO=Django==1.6.5
install:
  - pip install $DJANGO
  - "pip install . --use-mirrors"
  - "pip install -r testproject/requirements.txt --use-mirrors"
script:
  - cd testproject
  - python manage.py test fiber fiber_test
  - coverage run --source=fiber manage.py test fiber fiber_test
  - coverage report -m
after_success:
  - pip install -r requirements_coveralls.txt
  - coveralls
branches:
  only:
    - master
    - dev
    - python3
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.4.13
